name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0

      # Caching step
      - name: Cache OPAM packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.opam
            ~/.opam/*/lib
            ~/.opam/*/bin
          key: ${{ runner.os }}-opam-${{ hashFiles('**/opam.locked') }}-${{ hashFiles('**/dune') }}
          restore-keys: |
            ${{ runner.os }}-opam-${{ hashFiles('**/opam.locked') }}-
            ${{ runner.os }}-opam-
            ${{ runner.os }}-

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Update environment
        run: eval $(opam env)

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest
