name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up OPAM
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --disable-sandboxing -y
          eval $(opam env)

      # Caching step
      - name: Cache OPAM packages
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install dune
          opam install alcotest seq

      - name: Build project
        run: |
          eval $(opam env)
          dune build

      - name: Run tests
        run: dune runtest
