name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up OPAM
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --disable-sandboxing -y
          eval $(opam env)

      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install dune
          opam install alcotest -y
          opam install seq -y

      - name: Build project
        run: |
          eval $(opam env)
          dune build

      - name: Run tests
        run: dune runtest
