name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-test
          opam install dune -y

      - name: Update environment
        run: echo "$OPAM_SWITCH_PREFIX/bin" >> $GITHUB_PATH

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest
